---
galaxy_info:
  author: Andrew Rothstein
  description: installs wildfly
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - java
    - appserver

dependencies:
  - role: andrewrothstein.unarchive-deps
    version: v1.0.6
  - role: andrewrothstein.java-oracle-jre
    version: v1.0.2
  
