---
- name: download rpm
  become: yes
  become_user: root
  get_url: >-
    headers='Cookie:oraclelicense=accept-securebackup-cookie'
    url={{java_oracle_url}}
    dest=/tmp/{{java_oracle_rpm}}
    mode=0644

- name: install rpm
  become: yes
  become_user: root
  package: name=/tmp/{{java_oracle_rpm}} state=present
