---
galaxy_info:
  author: Andrew Rothstein
  description: installs Oracle Java JRE
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - java
    - jre
    - oracle

dependencies: []
  
