---
- hosts: ap_lx
  tasks:
  - name: create directory
    file:
      path: '/home/junichi/{{ instance_name }}'
      state: directory
      owner: junichi
      mode: 0755

  - name: copy file
    copy:
      src: /etc/hosts
      dest: /home/junichi/tmp/hosts
      owner: junichi
      mode: 0644
