---
- name: download tgz
  become: yes
  become_user: root
  get_url:
    url: '{{wildfly_tgz_url}}'
    dest: /tmp/{{wildfly_tgz}}
    mode: 0644

- name: unarchive
  become: yes
  become_user: root
  unarchive:
    copy: no
    src: /tmp/{{wildfly_tgz}}
    dest: '{{wildfly_install_parent_dir}}'
    creates: '{{wildfly_install_parent_dir}}/{{wildfly_name}}'

- name: link
  become: yes
  become_user: root
  file:
    src: '{{wildfly_install_parent_dir}}/{{wildfly_name}}'
    dest: '{{wildfly_install_parent_dir}}/wildfly'
    state: link

- name: add to path
  become: yes
  become_user: root
  with_items:
    - f: wildfly.sh
      d: /etc/profile.d
      m: 0644
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
    
