---
- hosts: ap_servers
  tasks:
  - name: create directory
    file:
      path: '/home/{{ ansible_user }}/{{ item }}'
      state: directory
      owner: '{{ ansible_user }}'
      mode: 0755
    with_items: "{{instance_name}}"

  - name: copy file
    copy:
      src: /etc/hosts
      dest: '/home/{{ ansible_user }}/tmp/hosts'
      owner: '{{ ansible_user }}'
      mode: 0644
